module.exports = {
  // Login page
  nameinput: "email",
  passinput: "password",
  submitBtn: "button#Myid",
  aSubmit: ".dropdown a",
  //Profitability
  buttonCreateReport: ".col-md-12 .btn-group button",
  contrAgentName: ".select2-search__field",
  contrDateFrom: "start",
  contrDateTo: "end",
  createBtn: ".btn-group .btn",

  //Client
  //Main info
  addClientBtn: "[data-target=\"#modalAddClient\"]",
  nameInputClient: "#main_name",
  countryInputClient: "#main_country",
  cityInputClient: "#main_city",
  addressInputClient: "#main_address",
  wedsiteInputClient: "8",
  commentInputClient: "9",
  createBtnClient:
    ".row .col-lg-12 .form-group .col-sm-8 .btn-group button.btn.btn-success",
  //legal info
  suggestionAddress: "#suggestion_address_value",
  tabLegalInfo: "[href=\"#tab-group-6\"]",
  suggestionOGRN: "#suggestion_ogrn",
  suggestion_inn: "#suggestion_inn",
  suggestion_state_registration_date: "#suggestion_state_registration_datele",
  suggestion_kpp: "#suggestion_kpp",
  suggestion_opf_code: "#suggestion_opf_code",
  suggestion_okved: "#suggestion_okved",
  suggestion_management_name: "#suggestion_management_name",
  tabOtherInfo: "[href=\"#tab-group-7\"]",
  inputItem: "",
  tabGlassSales: "[href=\"#tab-group-8\"]",
  tabSalesStat: "[href=\"#tab-group-9\"]",
  tabGenPro: "[href=\"#tab-group-10\"]",
  saveBtnSeasonality: "#seasonalityForm button",
  seasonalitySelectCompanyBasic: ".form-control.select_filter",
  inputsSeasonality: "#seasonalityForm input:not([type=\"hidden\"])",
  addBtnProject: "button[data-toggle=\"modal\"]",
  inputsProject1: ".form-horizontal .panel-body input[name=\"name\"]",
  inputsProject2: ".form-horizontal .panel-body input[name=\"square\"]",
  inputsProject3: ".form-horizontal .panel-body input[name=\"address\"]",
  inputsProject4: ".form-horizontal .panel-body input[name=\"term\"]",
  textareaProject: ".form-horizontal .panel-body textarea",
  selectProject: ".form-horizontal .panel-body #type_id",
  spanProject1: ".form-horizontal .panel-body #select2-stage_id-lg-container",
  spanProject2: ".form-horizontal .panel-body #select2-type2_id-08-container",
  spanProject3:
    ".form-horizontal .panel-body #select2-matching_status_id-3j-container",
  spanProject4:
    ".form-horizontal .panel-body #select2-subdivision_id-85-container",
  spanProject5: ".form-horizontal .panel-body #select2-sale_status_id-z3-container",
  spanProjectSelection: ".form-horizontal .panel-body .selection span[aria-activedescendant=\"select2-stage_id-lg-result-gxhh-8\"] span",
  addProjectBtn: ".form-horizontal .panel-footer .col-lg-2 button",
  printBtnProject: "#printTableProjects",
  inputsCompanies: "form.form-horizontal input:not([type=hidden]), form.form-horizontal textarea",
  selectsCompanies: "form.form-horizontal select",
  addBtnCompanies: "button[data-target=\"#modalAddCompany\"]",
  tabCompanies: "a[href=\"#tab-group-1\"], a[href=\"#tab-group-6\"]",
  appendBtnCompanies: ".form-group .btn-group .btn.btn-success",
  selectCompaniesTypeOfCompany: "//div[@id='modalAddCompany']/div[@role='document']//form[@role='form']/div[@class='panel-body']/div/div[1]/div/div//select[@name='5']/option[@value='6']",
  selectOptionCompaniesStatus: "//div[@id='modalAddCompany']/div[@role='document']//form[@role='form']/div[@class='panel-body']/div/div[1]/div/div//select[@name='6']/option[@value='19']",
  btnSucces: "button.btn.btn-success",
  inputsContacts: "form.form-horizontal input, form.form-horizontal textarea",
  selectOptionContactactsCompany: "//div[@id='modalAddContact']/div[@role='document']//form[@role='form']//select[@name='company_hash']/option[@value='226ac982-2b7f-11e8-a73a-704d7bb35db2']",
  selectOptionContactactsProjectType: "//div[@id='modalAddProject']/div[@role='document']/div[@class='modal-content']/form[@role='form']//select[@name='type_id']/option[@value='2']",
  selectOptionContactactsProjectStageOfProject: "//div[@id='modalAddProject']/div[@role='document']/div[@class='modal-content']/form[@role='form']//select[@name='stage_id']/option[@value='6']",
  selectOptionContactactsProjectTypeOfProject: "//div[@id='modalAddProject']/div[@role='document']/div[@class='modal-content']/form[@role='form']//select[@name='type2_id']/option[@value='5']",
  selectOptionContactactsProjectStatus: "//div[@id='modalAddProject']/div[@role='document']/div[@class='modal-content']/form[@role='form']//select[@name='matching_status_id']/option[@value='2']",
  selectOptionContactactsProjectDivision: "//div[@id='modalAddProject']/div[@role='document']/div[@class='modal-content']/form[@role='form']//select[@name='subdivision_id']/option[@value='3']",
  selectOptionContactactsProjectStatusSale: "//div[@id='modalAddProject']/div[@role='document']/div[@class='modal-content']/form[@role='form']//select[@name='sale_status_id']/option[@value='3']",
  tabsCalculations: "//div[@id='formCalculation']/div/ul[@class='nav nav-tabs']//a[@href='#tab-main-1'], //div[@id='formCalculation']/div/ul[@class='nav nav-tabs']//a[@href='#tab-main-2'], //div[@id='formCalculation']/div/ul[@class='nav nav-tabs']//a[@href='#tab-main-3']",
  formaCompleteProduct: "//form[@id='formCalculationInfo']//select[@name='form_id']/option[@value='2']",
  plusGlass: ".btn.w-xs.btn-success.btn-xs",
  glassOption: "/html//form[@id='formAddlGPList']//select[@name='glass_id']/option[@value='20']",
  tollingCheckbox: "input[name=\"take\"]",
};
